config/routes.rb
Rails.application.routes.draw do
  # get 'login'  => 'users#new'
  resources :users

  root 'games#index'

  get 'profile' => 'users#profile'

  put 'profile' => 'users#edit'

  get 'game' => 'games#index'

  get 'leaderboard' => 'games#leaderboard'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'login' => 'sessions#destroy'

  post 'game' => 'scores#win'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :games
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true
  has_many :scores
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :require_user, only: [:index, :show]

  def index
    @user = User.find(session[:user_id])
  end

  def leaderboard
    @users = User.all
    @scores = Score.all
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def win
    @score = Score.new(user_id: params[:user_id], completeness: params[:completeness], turns_taken: params[:turns_taken])
    if @score.save
      session[:score] = @score.completeness
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_username(params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/games'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session.clear
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/games'
    else
      redirect_to '/login'
    end
  end

  def profile
    @user = User.find(session[:user_id])
    @scores = Score.all
  end

  def edit
    @user = User.find(session[:user_id])
    @user.username = params[:user][:username]
    @user.save
    redirect_to '/profile'
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_leaderboard.html.haml
%ul.leader
  - @users.each do |user|
    %li#1.entry
      %i#1.fa.fa-trophy
      %h3#1 #{user.username}
      %span#1
        - sum = 0
        - (@scores.where(:user_id => user.id)).each do |score|
          - sum += score.completeness
        = sum

app/views/games/index.html.haml
#difficulty-buttons.h1-container
  %input{:type=>'button', :class=>'difficulty', :value=>'Easy'}
  %input{:type=>'button', :class=>'difficulty', :value=>'Medium'}
  %input{:type=>'button', :class=>'difficulty', :value=>'Hard'}
.board-wrap
  = tag("div", id: 'board-container', data: {user_id: @user.id})

app/views/games/leaderboard.html.haml
%body
  %header
    .h1-container
      %h1 The Game of Memory

  .title
    %h2
      Top Scores
      %i.fa.fa-star#left-star
      %i.fa.fa-star#right-star
  -# put dummy variables here
  %section.table
    .table-cell
      = render :partial => 'leaderboard'

app/views/layouts/application.html.haml
-# LOGIN PAGE



!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Open+Sans", :rel => "stylesheet"}/
    %title Memory Game
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    #win-modal.modal
      .modal-content
        %h1 You Won!
        %h3#attempts
        %input{:type=>'button', :class=>'play-again', :value=>'Play Again'}
    .container
    - if current_user
      %ul.user-prompts
        %p= link_to "#{current_user.username}", 'profile'
        %p= link_to "Game", 'game'
        %p= link_to "Leaderboard", 'leaderboard'
        %p= link_to "Log Out", login_path, method: "delete"
    - else
      %ul.user-prompts
    .container
      = yield

app/views/layouts/index.haml
!!! 5
%html(lang='en')
  %head
    %meta(charset="UTF-8")
    %meta(content='width=device-width, initial-scale=1' name='viewport')
    %link(rel='stylesheet'href='../src/js/vendor/jquery-ui.min.css')
    %link(rel='stylesheet'href='../lib/styles/main.min.css')
    %title The Game of Memory
  %body
    -# put dummy variables here
    %header
      .h1-container
        %h1 The Game of Memory
    %section.content-container







  %script(src="../src/js/vendor/jquery-3.1.1.min.js")
  %script(src="../src/js/vendor/jquery-ui.min.js")
  %script(src="../src/js/app.js")

app/views/layouts/userPage.haml
!!! 5
%html(lang='en' id="leaderboard")
  %head
    %meta(charset="UTF-8")
    %meta(content="width=device-width, initial-scale=1" name="viewport")
    -# %link(rel='stylesheet'href='../src/js/vendor/jquery-ui.min.css')
    -# %link(rel='stylesheet'href='../lib/styles/main.min.css')
    %link(href="https://fonts.googleapis.com/css?family=ABeeZee|Nunito" rel="stylesheet")
    -# %link(href="../lib/styles/vendor/font-awesome-4.6.3/css/font-awesome.min.css" rel="stylesheet")
    %title UserDetails:MemoryGame
  %body
    %header
      .h1-container
        %h1 The Game of Memory
      #userpage-container
        #userpage-title
          %h2
            Welcome, User!

        %aside#userpage-aside
          %nav
            #goto-leaderboard View Top Scores
            #goto-game Return To Game



        -# put dummy variables here
        %section.user-table
          .table-cell
            #user-score-div
              %h3 Your current total is 29 Points.
            %ul.user-details
              %li.user-email
                %i#1.fa.fa-envelope
                -# input fields will toggle readonly if edit button is pressed.
                %input#email{readonly:true, type:"text"} user@something.com
              %li.user-password
                %i#1.fa.fa-key
                %input#password{readonly:true, type:"password"} hopefully you can't read this.
              %li.user-twitter
                %i#1.fa.fa-twitter
                %input#twitter{readonly:true, type:"text"} @twitterhandle
              %li.user-facebook
                %i#1.fa.fa-facebook-official
                %input#facebook{readonly:true, type:"text"} facebook/page/user
                %button#user-details-edit Edit Your Information
                -#  submit button will toggle hidden if edit button is pressed.
                %button#user-details-submit.hidden Submit Changes
                -# if password has changed, a pop-up box should make your re-type it to confirm

app/views/scores/leaderboard.html.haml
!!!
%html
  %head
    %title LeaderBoard:MemoryGame
  %body
    %header
      .h1-container
        %h1 The Game of Memory

    .title
      %h2
        Top Scores
        %i.fa.fa-star#left-star
        %i.fa.fa-star#right-star
    -# put dummy variables here
    %section.table
      .table-cell
        %ul.leader
          %li.entry#1
            %i#1.fa.fa-trophy
            %h3#1 Person 1
            %span#1 29 points
          %li.entry#2
            %i#2.fa.fa-bookmark
            %h3#2 Person 2
            %span#1 27 points
          %li.entry#1
            %i#1.fa.fa-bookmark
            %h3#1 Person 3
            %span#1 24 points
          %li.entry#2
            %i#2.fa.fa-bookmark
            %h3#2 Person 4
            %span#1 20 points

app/views/users/profile.html.haml
- games = [{gameNum: '1', score: '67'},{gameNum: '2', score: '98'}]
- userInfo = [{name: 'marian', email: 'none@none.com', password: 'pw', currentScore: '33'}]
  %header
    .h1-container
      %h1 The Game of Memory
    #userpage-container
      #userpage-title
        %h2
          Welcome, User!

      %aside#userpage-aside
        %nav
          %button#goto-scores.view-scores View Scores
          %i.fa.fa-star

      %section#user-table
        #user-score-div
          %h3
            Current Total:
            #total-points
              - sum = 0
              - (@scores.where(:user_id => @user.id)).each do |score|
                - sum += score.completeness
              = sum
        %ul#user-details
          = form_for :user, url: profile_path, method: :put do |f|
            = f.text_field :username, :placeholder => "Username"
            = f.email_field :email, :placeholder => "Email"
            = f.password_field :password, :placeholder => "Password"
            = f.submit "Update account info", class: "btn-submit", id: 'button'
      %section.table#score-table.hidden
        .table-cell
        -unless games.empty?
          %ul.leader#scores-ul
            - (@scores.where(:user_id => @user.id)).each do |score|
            %li.entry
              %i.fa.fa-star
              %h3 Game Number #{score.id}
              %span#1 #{score.completeness} Points